version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./startup.sh:/startup.sh
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'

  open_web_ui:
    image: dyrnq/open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local
  open-webui:
    driver: local
